import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgQtqJVxwWhgsDoVb5jcw8MXV1XRnAh9s',
    appId: '1:293260329827:web:3ce6263c4f88f77db9c956',
    messagingSenderId: '293260329827',
    projectId: 'padhai-app-38dd0',
    authDomain: 'padhai-app-38dd0.firebaseapp.com',
    storageBucket: 'padhai-app-38dd0.firebasestorage.app',
    measurementId: 'G-E032MX943J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgQtqJVxwWhgsDoVb5jcw8MXV1XRnAh9s',
    appId:
        '1:293260329827:android:a1b2c3d4e5f6', // Placeholder, ideally generated by CLI
    messagingSenderId: '293260329827',
    projectId: 'padhai-app-38dd0',
    storageBucket: 'padhai-app-38dd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgQtqJVxwWhgsDoVb5jcw8MXV1XRnAh9s',
    appId:
        '1:293260329827:ios:a1b2c3d4e5f6', // Placeholder, ideally generated by CLI
    messagingSenderId: '293260329827',
    projectId: 'padhai-app-38dd0',
    storageBucket: 'padhai-app-38dd0.firebasestorage.app',
    iosBundleId: 'com.example.podcastmagic',
  );
}
